default_platform :ios

platform :ios do

    desc "Create signing certs and provisioning profiles if needed"
    lane :signing do
        app = "me.syan.LeFood"

        cert(team_id: "79RY8264V4", development: true)
        sigh(team_id: "79RY8264V4", app_identifier: app, platform: "ios",      development: true, force: true)
        sigh(team_id: "79RY8264V4", app_identifier: app, platform: "catalyst", development: true, force: true)

        cert(team_id: "79RY8264V4")
        sigh(team_id: "79RY8264V4", app_identifier: app, platform: "ios",      force: true)
        sigh(team_id: "79RY8264V4", app_identifier: app, platform: "catalyst", force: true)
    
        system "rm ../*.provisionprofile"
        system "rm ../*.mobileprovision"
        system "rm ../*.cer"
        system "rm ../*.p12"
        system "rm ../*.certSigningRequest"
    end

    def promptIncrementBuild
        if UI.confirm("Do you want to increase the build number before building the apps?")
            increment_build_number
        end
    end

    desc "Submit a new build"
    lane :beta do
        promptIncrementBuild

        build_app(
            scheme: "LeFood",
            output_directory: "./build",
            skip_profile_detection: true,
            export_method: "app-store",
            export_options: {
                method: "app-store",
                signingCertificate: "Apple Distribution",
                provisioningProfiles: {
                    "me.syan.LeFood" => "me.syan.LeFood AppStore"
                }
            }
        )
        upload_to_testflight(
            skip_waiting_for_build_processing: true,
        )
    end

    lane :screenshots do
        if UI.confirm("Redo screenshots?")
            snapshot

            # fix wrong screenshot resolutions...
            Dir.glob('screenshots/**/iPhone 15 Pro-*.png').each do |path|
                puts "Resizing #{path}"
                `mogrify -resize "1179x2556!" "#{path}"`
            end
        end

        deliver(
            app_identifier: 'me.syan.LeFood',
            force: true,
            platform: 'ios',
            skip_metadata: true,
            skip_app_version_update: true,
            overwrite_screenshots: true
        )
    end
end
